name: CMSE890Project
channels:
  - bioconda
  - conda-forge
dependencies:
  - python
  - snakemake
  - numpy
  - matplotlib
  - pytest
  - graphviz
# if you need to pip install anything: 
# -pip
pip: 
  - pytest
  - graphviz 


