# Configuration file 
# 
# Edit the following directory paths to represent where you want to store inputs 
# and outputs

input_dir: "input"
output_dir: "outputs"
log_dir: "logs"
resources:
  memory: 4000
  threads: 4
