#!/bin/bash
cat > cdc.in << EOF
CDCC 15C+D  ; N+C q=0,1,2
 &CDCC
   hcm=0.01  rmatch=-60 rasym=1000 accrcy=0.001 absend=-50
   elab=106.5
   jbord= 0 50
   jump= 1
   thmax=180 thinc=1 cutr=-10 smats=2 xstabl=1
   ncoul=0 reor=0 q=2
   /
 &NUCLEUS part='Proj' name='15C' charge=6 mass=15
                spin=0.5 parity=+1 be=1.21  n=2 l=0 j=0.5 /
 &NUCLEUS part='Core' name='14C' charge=6 mass=14 /
 &NUCLEUS part='Valence' name='neutron' charge=0 mass=1 spin=0.5/
 &NUCLEUS part='Target' name='deuteron' charge=1 mass=2 spin=0 /

 &BIN spin=0.5 parity=+1 start=0.001 step=1. end=12.6 energy=F l=0 j=0.5/
 &BIN /

 &POTENTIAL part='Proj' a1=15 rc=1.3 /
 &POTENTIAL part='Core' a1=14 rc=1.3 v=75.512 vr0=1.174 a=0.809 w=2.881 wr0=1.563 aw=0.811 /
 &POTENTIAL part='Valence' rc=1.3 v=73.69893075 vr0=0.63809075 a=0.2378085625 w=6.4428675 wr0=1.136442 aw=0.472194 wd=>
aso=0.625115 /
 &POTENTIAL part='Gs' rc=1.3 v=44.675 vr0=0.1173 a=0.4539 vso=8.060 rso0=1.210 aso=0.650 /

EOF
